wandb:
    api_key: "75453b8f1fb73877e5729903eb4c5451e984fb58"
    project: "Vi-SepReformer-TSE" 
    entity: "quangduy162003-utc"
    resume: False
    log: "gradients"
    log_freq: 4
# ------------------------------------------------------------ #
dataset:
    dataset_size: 
        train: 51 # 20 # size/n_gpus > 1000
        test: 10 #24
        val: 10 #24
    wave_len: 32000
    sample_rate: 8000
    
    speech_metadata_paths: 
        - [1, 'LibriSpeech_metadata.csv']
# ------------------------------------------------------------ #
dataloader:
    batch_size_per_gpu: 1
    num_workers: 1
    # pin_memory: false
    # persistent_workers: false
# ------------------------------------------------------------ #
model:
    num_stages: &var_model_num_stages 4 # R
    num_spks: &var_model_num_spks 2
    module_audio_enc:
        in_channels: 1
        out_channels: &var_model_audio_enc_out_channels 256
        kernel_size: &var_model_audio_enc_kernel_size 16 # L 
        stride: &var_model_audio_enc_stride 4 # S
        groups: 1
        bias: false
    module_feature_projector:
        num_channels: *var_model_audio_enc_out_channels 
        in_channels: *var_model_audio_enc_out_channels
        out_channels: &feature_projector_out_channels 128 # F # Switch to Tiny: 64, Base: 128, Large: 256 
        kernel_size: 1
        bias: false
    module_separator:
        num_stages: *var_model_num_stages
        relative_positional_encoding:
            in_channels: *feature_projector_out_channels
            num_heads: 8
            maxlen: 2000
            embed_v: false
        enc_stage:
            global_blocks:
                in_channels: *feature_projector_out_channels
                num_mha_heads: 8
                dropout_rate: 0.05
            local_blocks:
                in_channels: *feature_projector_out_channels
                kernel_size: 65
                dropout_rate: 0.05
            down_conv_layer:
                in_channels: *feature_projector_out_channels
                samp_kernel_size: &var_model_samp_kernel_size 5
        spk_split_stage:
            in_channels: *feature_projector_out_channels
            num_spks: *var_model_num_spks
        simple_fusion:
            out_channels: *feature_projector_out_channels
        dec_stage:
            num_spks: *var_model_num_spks
            global_blocks:
                in_channels: *feature_projector_out_channels
                num_mha_heads: 8
                dropout_rate: 0.05
            local_blocks:
                in_channels: *feature_projector_out_channels
                kernel_size: 65
                dropout_rate: 0.05
            spk_attention:
                in_channels: *feature_projector_out_channels
                num_mha_heads: 8
                dropout_rate: 0.05
    module_output_layer:
        in_channels: *var_model_audio_enc_out_channels
        out_channels: *feature_projector_out_channels
        num_spks: *var_model_num_spks
    module_audio_dec:
        in_channels: *var_model_audio_enc_out_channels
        out_channels: 1
        kernel_size: *var_model_audio_enc_kernel_size
        stride: *var_model_audio_enc_stride
        bias: false
# ------------------------------------------------------------ #
criterion:
    name: ["PIT_SISNR_mag", "PIT_SISNR_time"]
    PIT_SISNR_mag:
        frame_length: 512
        frame_shift: 128
        window: 'hann'
        num_stages: *var_model_num_stages
        num_spks: *var_model_num_spks
        mel_opt: false
    PIT_SISNR_time:
        num_spks: *var_model_num_spks
    PIT_SISNRi:
        num_spks: *var_model_num_spks
    PIT_SDRi:
        dump: 0
# ------------------------------------------------------------ #
optimizer:
    name: ["AdamW"]
    AdamW:
        lr: 1.0e-3
        weight_decay: 1.0e-2
# ------------------------------------------------------------ #
scheduler:
    name: ["ReduceLROnPlateau", "WarmupConstantSchedule"] 
    ReduceLROnPlateau:
        mode: "min"
        min_lr: 1.0e-10
        factor: 0.8
        patience: 2
    WarmupConstantSchedule:
        warmup_steps: 1000
engine:
    max_epoch: 200
    gpus: 1
    mvn: false
    clip_norm: 5
    start_scheduling: 50
    save_checkpoint_freq: 1
